run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused
    - errorlint

linters-settings:
  staticcheck:
    checks: ["SA*", "S1*"]
  errorlint:
    errorf: true
    comparison: true
    asserts: true
